import type { ModelInfo } from "@cobeing/shared";

export const OPENAI_MODELS: ModelInfo[] = [
  {
    id: "gpt-4o",
    name: "GPT-4o",
    provider: "openai",
    contextWindow: 128000,
    maxOutput: 16384,
    supportsTools: true,
    supportsVision: true,
    tags: ["flagship", "vision"],
  },
  {
    id: "gpt-4o-mini",
    name: "GPT-4o Mini",
    provider: "openai",
    contextWindow: 128000,
    maxOutput: 16384,
    supportsTools: true,
    supportsVision: true,
    tags: ["fast", "vision"],
  },
  {
    id: "gpt-4.1",
    name: "GPT-4.1",
    provider: "openai",
    contextWindow: 1047576,
    maxOutput: 32768,
    supportsTools: true,
    supportsVision: true,
    tags: ["flagship", "coding", "vision"],
  },
  {
    id: "gpt-4.1-mini",
    name: "GPT-4.1 Mini",
    provider: "openai",
    contextWindow: 1047576,
    maxOutput: 32768,
    supportsTools: true,
    supportsVision: true,
    tags: ["coding", "vision"],
  },
  {
    id: "o3-mini",
    name: "O3 Mini",
    provider: "openai",
    contextWindow: 200000,
    maxOutput: 100000,
    supportsTools: true,
    supportsVision: false,
    tags: ["reasoning", "coding"],
  },
  {
    id: "o4-mini",
    name: "O4 Mini",
    provider: "openai",
    contextWindow: 200000,
    maxOutput: 100000,
    supportsTools: true,
    supportsVision: true,
    tags: ["reasoning", "coding", "vision"],
  },
];
