import type { ModelInfo } from "@cobeing/shared";

export const ZHIPU_MODELS: ModelInfo[] = [
  {
    id: "glm-4-plus",
    name: "GLM-4 Plus",
    provider: "zhipu",
    contextWindow: 131072,
    maxOutput: 4096,
    supportsTools: true,
    supportsVision: true,
    tags: ["flagship"],
  },
  {
    id: "glm-4-air",
    name: "GLM-4 Air",
    provider: "zhipu",
    contextWindow: 131072,
    maxOutput: 4096,
    supportsTools: true,
    supportsVision: false,
    tags: ["fast"],
  },
  {
    id: "glm-4-flash",
    name: "GLM-4 Flash",
    provider: "zhipu",
    contextWindow: 131072,
    maxOutput: 4096,
    supportsTools: true,
    supportsVision: false,
    tags: ["fast"],
  },
  {
    id: "glm-4-long",
    name: "GLM-4 Long",
    provider: "zhipu",
    contextWindow: 1048576,
    maxOutput: 4096,
    supportsTools: true,
    supportsVision: false,
    tags: ["long-context"],
  },
  {
    id: "glm-4v-plus",
    name: "GLM-4V Plus",
    provider: "zhipu",
    contextWindow: 131072,
    maxOutput: 4096,
    supportsTools: true,
    supportsVision: true,
    tags: ["vision"],
  },
  {
    id: "codegeex-4",
    name: "CodeGeeX 4",
    provider: "zhipu",
    contextWindow: 131072,
    maxOutput: 4096,
    supportsTools: true,
    supportsVision: false,
    tags: ["coding"],
  },
];
