FROM cobeing-sandbox:python

# Go 1.22
RUN wget -q https://go.dev/dl/go1.22.4.linux-amd64.tar.gz && \
    tar -C /usr/local -xzf go1.22.4.linux-amd64.tar.gz && \
    rm go1.22.4.linux-amd64.tar.gz
ENV PATH=$PATH:/usr/local/go/bin

# Ruby
RUN apt-get update && \
    apt-get install -y ruby && \
    rm -rf /var/lib/apt/lists/*

CMD ["bash"]
